import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='Snap',
                  resource_url='https://snap.berkeley.edu/'),
    course.Course(period=2,
                  name='AP English Literature and Composition',
                  teacher_name='Ms. Wilson',
                  resource_name='Capstone Blogs',
                  resource_url='https://2wendyt2018.blogspot.com/'),
    course.Course(period=3,
                  name='AP Calculus AB',
                  teacher_name='Mr. Wai',
                  resource_name='Calculus Textbook',
                  resource_url='http://hsebooks.kendallhunt.com/calc_se/ebook/kh.html'),
    course.Course(period=4,
                  name='Student Leadership',
                  teacher_name='Ms. Nelson',
                  resource_name='CADA',
                  resource_url='https://secure.cada1.org/i4a/pages/index.cfm?pageid=3461'),
    course.Course(period=5,
                  name='American Government',
                  teacher_name='Mr. Kelly',
                  resource_name='The Constitution',
                  resource_url='https://www.whitehouse.gov/about-the-white-house/the-constitution/'),
    course.Course(period=6,
                  name='Teacher Aide',
                  teacher_name='Ms. Belli',
                  resource_name='FAFSA',
                  resource_url='https://fafsa.ed.gov/'),
]
